{"uuid": "b7eae587-fd54-449e-89e5-05e5bb6b36f1", "children": ["d1e4ddb7-2ab7-4b82-b4d7-9ff75e70a677", "b7e15f81-6d79-4ca2-931c-acc903962fc3", "5c51958c-8fd6-4c01-873c-decabc2c8d30", "823d1d04-1e3f-467d-a3dd-415244359261"], "befores": [{"name": "_init_desktop_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\n<head>\n   <title>Status page</title>\n</head>\n<body style=\"font-family: sans-serif;\">\n<p style=\"font-size: 1.2em;font-weight: bold;margin: 1em 0px;\">Not Found</p>\n<p>The server has not found anything matching the request URI</p>\n<p>You can get technical details <a href=\"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5\">here</a>.<br>\nPlease continue your visit at our <a href=\"/\">home page</a>.\n</p>\n</body>\n</html>\n\n\n", "trace": "  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\test_cases\\conftest.py\", line 100, in _init_desktop_driver\n    event_driver = get_desktop_driver()\n                   ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\test_cases\\conftest.py\", line 204, in get_desktop_driver\n    driver = selenium.webdriver.Remote(get_data('WinAppDriverService'), dc)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\development\\PythonAtidAutomation\\final_project_infrastructure\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 208, in check_response\n    raise exception_class(value)\n"}, "start": 1730287460718, "stop": 1730287460748}], "start": 1730287460718, "stop": 1730287461138}